export const animals = [
	{
		id: 1,
		name: "Red CR",
		description: "Perfect shape and overall fit",
		image: "https://res.cloudinary.com/hostingimagesservice/image/upload/v1718551370/cow-354428_1280_ky6m3a.jpg",
		price: 125000,
		ownerName: "Minhaz",
		ownerPhoto: "https://randomuser.me/api/portraits/men/9.jpg",
		createdAt: "1 month ago",
		family: "High breed",
		type: "Cow",
		height: 1.4732,
	},
	{
		id: 2,
		name: "Red CR",
		description: "Perfect shape and overall fit",
		image: "https://res.cloudinary.com/hostingimagesservice/image/upload/v1718551370/cow-354428_1280_ky6m3a.jpg",
		price: 125000,
		ownerName: "Minhaz",
		ownerPhoto: "https://randomuser.me/api/portraits/men/9.jpg",
		createdAt: "1 month ago",
		family: "High breed",
		type: "Cow",
		height: 1.4732, // (meter)
	},
	{
		family: "High breed",
		name: "Red CR",
		description: "Perfect shape and overall fit",
		image: "https://res.cloudinary.com/hostingimagesservice/image/upload/v1718551370/cow-354428_1280_ky6m3a.jpg",
		price: 125000,
		ownerName: "Minhaz",
		ownerPhoto: "https://randomuser.me/api/portraits/men/9.jpg",
		createdAt: "1 month ago",
		id: 3,
		type: "Cow",
		height: 1.4732,
	},
	{
		id: 4,
		name: "Red CR",
		description: "Perfect shape and overall fit",
		image: "https://res.cloudinary.com/hostingimagesservice/image/upload/v1718551370/cow-354428_1280_ky6m3a.jpg",
		price: 125000,
		ownerName: "Minhaz",
		ownerPhoto: "https://randomuser.me/api/portraits/men/9.jpg",
		createdAt: "1 month ago",
		family: "High breed",
		type: "Cow",
		height: 1.4732,
	},
	{
		id: 8,
		name: "Red CR",
		description: "Perfect shape and overall fit",
		image: "https://res.cloudinary.com/hostingimagesservice/image/upload/v1718551370/cow-354428_1280_ky6m3a.jpg",
		price: 125000,
		ownerName: "Minhaz",
		ownerPhoto: "https://randomuser.me/api/portraits/men/9.jpg",
		createdAt: "1 month ago",
		family: "High breed",
		type: "Cow",
		height: 1.4732,
	},
];
